#!/usr/bin/env python

import os

MODEL_CACHE = "pretrained_models"

if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

os.system("git lfs clone --branch fp16 https://huggingface.co/runwayml/stable-diffusion-v1-5/ pretrained_models/stable-diffusion-v1-5/")
os.system("git lfs clone https://huggingface.co/stabilityai/sd-vae-ft-mse-original pretrained_models/sd-vae-ft-mse")
os.system("git lfs clone https://huggingface.co/zcxu-eric/MagicAnimate pretrained_models/MagicAnimate")

# Controlnet-Openpose
os.system("cd pretrained_models/MagicAnimate && mkdir openpose_controlnet")
os.system("cd pretrained_models/MagicAnimate/openpose_controlnet && wget https://huggingface.co/lllyasviel/sd-controlnet-openpose/resolve/main/diffusion_pytorch_model.safetensors")
os.system("cd pretrained_models/MagicAnimate/openpose_controlnet && wget https://huggingface.co/lllyasviel/sd-controlnet-openpose/resolve/main/config.json")

os.system("git clone https://github.com/magic-research/magic-animate.git")